const $=id=>document.getElementById(id);let token=localStorage.getItem("tf_token"),user=JSON.parse(localStorage.getItem("tf_user")||"null"),tasks=[],mode="login",editId=null;
function toast(m){$("toast").textContent=m;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2400)}
function screen(){ $("auth").classList.toggle("hide",!!token);$("app").classList.toggle("hide",!token);if(user)$("welcome").textContent=`Hi, ${user.name}`}
async function api(url,opt={}){opt.headers={"Content-Type":"application/json",...(opt.headers||{})};if(token)opt.headers.Authorization=`Bearer ${token}`;const r=await fetch(url,opt),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||"Request failed");return d}
function authMode(m){mode=m;$("loginTab").classList.toggle("active",m==="login");$("registerTab").classList.toggle("active",m==="register");$("nameBox").classList.toggle("hide",m!=="register");$("authBtn").textContent=m==="register"?"Create account":"Login";$("authForm").reset()}
$("loginTab").onclick=()=>authMode("login");$("registerTab").onclick=()=>authMode("register");
$("authForm").onsubmit=async e=>{e.preventDefault();try{let body={email:$("email").value.trim(),password:$("password").value};if(mode==="register")body.name=$("name").value.trim();let d=await api(`/api/auth/${mode==="register"?"register":"login"}`,{method:"POST",body:JSON.stringify(body)});token=d.token;user=d.user;localStorage.setItem("tf_token",token);localStorage.setItem("tf_user",JSON.stringify(user));screen();toast(d.message);load()}catch(e){toast(e.message)}};
async function load(){try{let q=new URLSearchParams({status:$("filter").value,search:$("search").value.trim()});tasks=await api(`/api/tasks?${q}`);render()}catch(e){toast(e.message)}}
function render(){let list=$("tasks");list.innerHTML="";$("empty").classList.toggle("hide",tasks.length>0);$("total").textContent=tasks.length;$("todo").textContent=tasks.filter(x=>x.status==="Todo").length;$("progress").textContent=tasks.filter(x=>x.status==="In Progress").length;$("done").textContent=tasks.filter(x=>x.status==="Completed").length;tasks.forEach(t=>{let d=document.createElement("div");d.className=`task ${t.status==="Completed"?"completed":""}`;let due=t.dueDate?new Date(t.dueDate).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"No due date";d.innerHTML=`<div><h3>${esc(t.title)}</h3><p>${esc(t.description||"No description added.")}</p><div class="meta"><span class="badge">${esc(t.status)}</span><span class="badge ${t.priority.toLowerCase()}">${esc(t.priority)} priority</span><span class="badge">Due: ${due}</span></div></div><div class="taskActions"><button data-a="status" data-id="${t._id}">${t.status==="Completed"?"Reopen":"Complete"}</button><button data-a="edit" data-id="${t._id}">Edit</button><button class="delete" data-a="delete" data-id="${t._id}">Delete</button></div>`;list.appendChild(d)})}
function esc(s){return String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function openModal(t){editId=t?. _id||null;$("modalTitle").textContent=editId?"Edit Task":"Create Task";$("taskId").value=editId||"";$("title").value=t?.title||"";$("description").value=t?.description||"";$("priority").value=t?.priority||"Medium";$("status").value=t?.status||"Todo";$("dueDate").value=t?.dueDate?new Date(t.dueDate).toISOString().slice(0,10):"";$("modal").classList.remove("hide")}
function closeModal(){$("modal").classList.add("hide");$("taskForm").reset();editId=null}
$("newTask").onclick=()=>openModal();$("close").onclick=closeModal;$("cancel").onclick=closeModal;
$("taskForm").onsubmit=async e=>{e.preventDefault();let body={title:$("title").value.trim(),description:$("description").value.trim(),priority:$("priority").value,status:$("status").value,dueDate:$("dueDate").value||null};try{await api(`/api/tasks${editId?"/"+editId:""}`,{method:editId?"PUT":"POST",body:JSON.stringify(body)});closeModal();toast(editId?"Task updated.":"Task created.");load()}catch(e){toast(e.message)}};
$("tasks").onclick=async e=>{let b=e.target.closest("button[data-a]");if(!b)return;let t=tasks.find(x=>x._id===b.dataset.id);try{if(b.dataset.a==="edit")return openModal(t);if(b.dataset.a==="delete"){if(!confirm("Delete this task?"))return;await api(`/api/tasks/${t._id}`,{method:"DELETE"});toast("Task deleted.")}else{await api(`/api/tasks/${t._id}/status`,{method:"PATCH",body:JSON.stringify({status:t.status==="Completed"?"Todo":"Completed"})});toast("Task status updated.")}load()}catch(e){toast(e.message)}};
$("filter").onchange=load;let timer;$("search").oninput=()=>{clearTimeout(timer);timer=setTimeout(load,300)};$("logout").onclick=()=>{token=null;user=null;localStorage.clear();screen()};screen();if(token)load();