require("dotenv").config();
const express=require("express"), mongoose=require("mongoose"), path=require("path");
const authRoutes=require("./routes/authRoutes"), taskRoutes=require("./routes/taskRoutes");
const app=express(), PORT=process.env.PORT||5000;
app.use(express.json());
app.use("/api/auth",authRoutes);
app.use("/api/tasks",taskRoutes);
app.use(express.static(path.join(__dirname,"..","frontend")));
app.get("*",(req,res,next)=>req.path.startsWith("/api/")?next():res.sendFile(path.join(__dirname,"..","frontend","index.html")));
mongoose.connect(process.env.MONGO_URI).then(()=>app.listen(PORT,()=>console.log(`TaskFlow: http://localhost:${PORT}`))).catch(e=>{console.error("MongoDB error:",e.message);process.exit(1)});